#!/bin/bash
##
## This script allows the user to update the lab wiki files.
## Joshua Wright, 3/19/2019
##
## Revisions:
##  + 20190802 - Get an IP automatically with updating
##

# Branch to use for content
GITBRANCH="MinorUpdate2019.2"

testconn() {
    ping -c 3 8.8.8.8 >/dev/null
    ret=$?
    if [ $ret -ne 0 ] ; then
        ping -c 3 4.4.4.4 >/dev/null
        ret=$?
        if [ $ret -ne 0 ] ; then
            echo "Unable to reach Internet sites to confirm connectivity." 1>&2
            errnotconnected
        fi
    fi
    echo "Connected."
    return
}

exiterr() {
    echo "" 1>&2
    echo "$1" 1>&2
    echo "" 1>&2
    echo "Please contact an instructor or TA for assistance." 1>&2
    exit -1
}

errnotconnected() {
    echo "" 1>&2
    echo "It looks like your system isn't connected to the Internet. Please see the lab" 1>&2
    echo "manual for steps to connect this virtual machine to the network." 1>&2
    echo "" 1>&2
    echo "If you continue to have trouble, please contact an instructor or email " 1>&2
    echo "virtual-labs-support@sans.org. Thank you!" 1>&2
    exit 1
}

errgithub() {
    echo "" 1>&2
    echo "There is an unexpected error with Git." 1>&2
    echo "" 1>&2
    echo "Please contact an instructor or email virtual-labs-support@sans.org." 1>&2
    echo "Thank you!" 1>&2
    exit 1
}
GITURL="ssh://git@github.com/joswr1ght/SANS-504-Student-Wiki"
BASEDIR="/home/sec504"
GITDIR="${BASEDIR}/wiki"

if [ $UID -eq 0 ] ; then
    echo ""
    echo "Please don't run this script as root. Exit your root shell, then try again."
    exit 1
fi

### Modified assuming VM uses NAT interface; obtain IP automatically
sudo service networking stop || exiterr "Unable to stop the networking service."
sudo dhclient eth0 1>&2 2>/dev/null || exiterr "Unable to obtain a DHCP address."
testconn # Exits if no connectivity


# Make sure the path exists first
if [ ! -d "$GITDIR" ] ; then
    mkdir -p $BASEDIR || { echo "ERROR: Cannot create the directory $BASEDIR." 1>&2 ; exit 1; }
    cd $BASEDIR|| { echo "ERROR: Cannot change to the directory $BASEDIR." 1>&2 ; exit 1; }
    echo Cloning $GITURL
    git clone $GITURL wiki >/dev/null || { errgithub; exit 1; }
    git pull
    git checkout origin/$GITBRANCH >/dev/null 2>&1 || { errgithub; exit 1; }
    git lfs install >/dev/null
fi


# Set CWD
cd $GITDIR || { echo "ERROR: Cannot change to $GITDIR. Remove the directory and try again." 1>&2 ; exit 1; }

echo "Updating lab wiki files... "
git checkout $GITBRANCH >/dev/null 2>&1 || { errgithub; exit 1; }
git reset HEAD --hard >/dev/null || { echo "ERROR: Cannot reset lab repository." 1>&2 ; exit 1; }
git pull >/dev/null 2>&1 || { errgithub; exit; }

### Modified assuming VM uses NAT interface; revert to static IP
sudo killall dhclient
sudo ifconfig eth0 0.0.0.0
sudo service networking start || exiterr "Unable to start the networking service. Please reboot."

echo "Done."
